onboarding = false

[terminal]
default_shell = "/bin/zsh"

[keys]
prefix = "ctrl+a"
goto = "prefix+shift+k"
new_tab = "prefix+t"
new_workspace = "prefix+w"
workspace_picker = "prefix+ctrl+w"
navigate_workspace_down = "j"
navigate_pane_down = "ctrl+j"

[[keys.command]]
key = "prefix+k"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "command prompt"
width = "80%"
height = "80%"

[theme]
name = "solarized-light"
auto_switch = true
light_name = "solarized-light"
dark_name = "nord"