onboarding = false

[terminal]
default_shell = "/bin/zsh"

[keys]
prefix = "ctrl+a"
new_tab = "prefix+w"
workspace_picker = "prefix+ctrl+w"
navigate_workspace_down = "j"
navigate_pane_down = "ctrl+j"

[theme]
name = "solarized-light"
auto_switch = true
light_name = "solarized-light"
dark_name = "nord"